/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    author: Author;
    'blog-categories': BlogCategory;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    author: AuthorSelect<false> | AuthorSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'resource-page': ResourcePage;
    'service-page': ServicePage;
    'about-page': AboutPage;
    'home-page': HomePage;
  };
  globalsSelect: {
    'resource-page': ResourcePageSelect<false> | ResourcePageSelect<true>;
    'service-page': ServicePageSelect<false> | ServicePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "author".
 */
export interface Author {
  id: number;
  name: string;
  designation: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  author: number | Author;
  categories?: (number | BlogCategory)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  isFeatured?: boolean | null;
  isTrending?: boolean | null;
  /**
   * Estimated read time in minutes
   */
  readTime?: number | null;
  tableOfContents?:
    | {
        label: string;
        /**
         * The ID of the section (e.g. #executive-summary)
         */
        anchor: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'author';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "author_select".
 */
export interface AuthorSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  isFeatured?: T;
  isTrending?: T;
  readTime?: T;
  tableOfContents?:
    | T
    | {
        label?: T;
        anchor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-page".
 */
export interface ResourcePage {
  id: number;
  hero?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  statutoryForms?: {
    title?: string | null;
    primaryForm?: {
      version?: string | null;
      title?: string | null;
      description?: string | null;
      buttonText?: string | null;
      file?: (number | null) | Media;
    };
    secondaryForm?: {
      title?: string | null;
      description?: string | null;
      buttonText?: string | null;
      link?: string | null;
    };
    additionalDownloads?:
      | {
          title: string;
          file: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  faqsSection?: {
    title?: string | null;
    description?: string | null;
    questions?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-page".
 */
export interface ServicePage {
  id: number;
  hero?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  servicesGrid?: {
    services?:
      | {
          title: string;
          description?: string | null;
          icon?: ('MdOutlineAccountBalance' | 'MdOutlineGavel' | 'MdOutlineQueryStats' | 'MdOutlinePayments') | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  sectorSpecialization?: {
    badge?: string | null;
    title?: string | null;
    /**
     * This section requires exactly 3 sectors to maintain the grid layout.
     */
    sectors?:
      | {
          title: string;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  icanFaq?: {
    title?: string | null;
    description?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    description?: string | null;
    primaryButton?: {
      text?: string | null;
      link?: string | null;
    };
    secondaryButton?: {
      text?: string | null;
      link?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    highlightText?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  foundation?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    vision?: {
      title?: string | null;
      description?: string | null;
    };
    mission?: {
      title?: string | null;
      description?: string | null;
    };
    pillars?:
      | {
          title: string;
          description: string;
          icon?: ('MdOutlineGavel' | 'MdOutlinePrecisionManufacturing') | null;
          id?: string | null;
        }[]
      | null;
    stewardship?: {
      title?: string | null;
      description?: string | null;
    };
  };
  leadership?: {
    badge?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    description?: string | null;
    leaders?:
      | {
          name: string;
          role: string;
          description: string;
          quote: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  accreditations?: {
    badge?: string | null;
    items?:
      | {
          title: string;
          iconType: 'text' | 'icon';
          iconText?: string | null;
          icon?: ('MdOutlineVerifiedUser' | 'MdOutlineLanguage') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    primaryButton?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryButton?: {
      text?: string | null;
      href?: string | null;
    };
    backgroundImage?: (number | null) | Media;
  };
  complianceBadge?: {
    badge?: string | null;
    title?: string | null;
    badges?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          icon: 'MdOutlineAccountBalance' | 'MdOutlineGavel' | 'MdOutlineQueryStats' | 'MdOutlinePayments';
          title: string;
          description: string;
          points?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          buttonText: string;
          buttonLink: string;
          id?: string | null;
        }[]
      | null;
  };
  ourImpact?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    testimonial?: {
      quote?: string | null;
      authorInitials?: string | null;
      authorName?: string | null;
      authorRole?: string | null;
    };
    image?: (number | null) | Media;
  };
  latestInsights?: {
    badge?: string | null;
    title?: string | null;
    linkText?: string | null;
    linkUrl?: string | null;
    /**
     * Select up to 3 articles to display in this section. If left empty, the most recent articles will be shown.
     */
    selectedArticles?: (number | Blog)[] | null;
  };
  finalCta?: {
    title?: string | null;
    description?: string | null;
    primaryButton?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryButton?: {
      text?: string | null;
      href?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-page_select".
 */
export interface ResourcePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  statutoryForms?:
    | T
    | {
        title?: T;
        primaryForm?:
          | T
          | {
              version?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              file?: T;
            };
        secondaryForm?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              link?: T;
            };
        additionalDownloads?:
          | T
          | {
              title?: T;
              file?: T;
              id?: T;
            };
      };
  faqsSection?:
    | T
    | {
        title?: T;
        description?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-page_select".
 */
export interface ServicePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  servicesGrid?:
    | T
    | {
        services?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  sectorSpecialization?:
    | T
    | {
        badge?: T;
        title?: T;
        sectors?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  icanFaq?:
    | T
    | {
        title?: T;
        description?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        primaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        highlightText?: T;
        backgroundImage?: T;
      };
  foundation?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        vision?:
          | T
          | {
              title?: T;
              description?: T;
            };
        mission?:
          | T
          | {
              title?: T;
              description?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        stewardship?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  leadership?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleLine2?: T;
        description?: T;
        leaders?:
          | T
          | {
              name?: T;
              role?: T;
              description?: T;
              quote?: T;
              image?: T;
              id?: T;
            };
      };
  accreditations?:
    | T
    | {
        badge?: T;
        items?:
          | T
          | {
              title?: T;
              iconType?: T;
              iconText?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        primaryButton?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryButton?:
          | T
          | {
              text?: T;
              href?: T;
            };
        backgroundImage?: T;
      };
  complianceBadge?:
    | T
    | {
        badge?: T;
        title?: T;
        badges?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
            };
      };
  ourImpact?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        testimonial?:
          | T
          | {
              quote?: T;
              authorInitials?: T;
              authorName?: T;
              authorRole?: T;
            };
        image?: T;
      };
  latestInsights?:
    | T
    | {
        badge?: T;
        title?: T;
        linkText?: T;
        linkUrl?: T;
        selectedArticles?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        description?: T;
        primaryButton?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryButton?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}